### ISSUE TITLE
Vergeten p tag aftesluiten

### ISSUE THREAD

**Issue by Daan645** [OniWithTheHoodie/the-startup-responsive-interactieve-website#11]
Je bent vergeten p tag aftesluiten

https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blame/3c83410a23d401891234d582a6847431b3911acd/index.html#L27C9-L27C79

**Comment by OniWithTheHoodie** [comment]
https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blob/d1ae0bc912317c8ed5fe15035c7b010e2f1e17ec/index.html#L59 

Ik heb het aangepast
