### ISSUE TITLE
De namen van de variabels verbeteren

### ISSUE THREAD

**Issue by Davidvboxt** [OniWithTheHoodie/the-startup-responsive-interactieve-website#4]
https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blob/7e2cf728bfc13455b45e7ee5a7e2f7219bfbbf4a/assets/style.css#L4

Probeer een primaire en secondaire variabel kleur te maken. Dit zorgt ervoor dat als er een moment komt dat de kleur die je gebruikt veranderd je alleen die kleur hoeft te veranderen en niet de naam van de variabel ervan.

**Comment by OniWithTheHoodie** [comment]
https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blob/d1ae0bc912317c8ed5fe15035c7b010e2f1e17ec/assets/style.css#L13-L14

is gepudate
